# Generated by Django 4.2.9 on 2024-01-15 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0002_rename_category_name_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='price_total',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='price_total',
        ),
        migrations.AddField(
            model_name='purchases',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sales',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='firm',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
