# Generated by Django 4.2.9 on 2024-01-19 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_purchases_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='is_deleted',
        ),
    ]
